name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Sigmasigmaboy/Dockerfile --tag my-image-name:$(date +%s)

    - name: Save Docker image to tarball
      run: docker save my-image-name:$(date +%s) -o my-image.tar

    - name: Upload Docker image as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: my-image.tar
